INSERT INTO `utilisateur` (`nom`,`prenom`,`mail`,`mdp`) VALUES ("Caleb","Summer","vitae.orci@ligulaconsectetuer.ca","STI65EHJ0QN"),("Yetta","Barrett","sapien.cursus@vitaesodalesat.com","SVS34KVD8EN"),("Howard","Kylie","ac.mattis@quamelementumat.org","LVU96JBL4LL"),("Clementine","Kasimir","Ut@ut.ca","WFY81HFX7GT"),("Sigourney","Hermione","orci.quis.lectus@dictum.co.uk","JGJ04KXO6CZ"),("Jaime","Desirae","a.tortor.Nunc@in.ca","LFC72AVR6AW"),("Craig","Farrah","risus.In@hymenaeosMaurisut.net","PWD85PEI9GC"),("Melvin","Camille","sed.sem.egestas@in.net","KSF02AIE2UI"),("Orlando","Stella","ultricies.sem.magna@velitjusto.com","BXH36NEX6AL"),("Kiara","Wylie","congue.a@sitamet.org","CLY85CNW9KJ");
INSERT INTO `utilisateur` (`nom`,`prenom`,`mail`,`mdp`) VALUES ("Tasha","Jasper","lacinia.Sed.congue@Nulla.org","XVE69YYV6WD"),("Adara","Jaquelyn","blandit.congue.In@et.ca","JVA79OTF8XE"),("Alexa","Lee","sem.mollis@tristiquepellentesque.ca","JLC61QTU3RA"),("Quin","Charles","ridiculus.mus.Proin@vitaesodales.co.uk","QJG88JXY9QE"),("Keane","Jesse","Morbi@VivamusrhoncusDonec.org","RNY26PJO8AQ"),("Marsden","Britanney","ante.dictum.cursus@aliquetodioEtiam.org","HWF83ZMV4JY"),("Holmes","Abbot","Duis@euenimEtiam.com","MQM53NPL0KT"),("Tucker","Matthew","nonummy.ac.feugiat@Duiselementumdui.org","ESK23AWO7EZ"),("Aaron","Hasad","a.tortor.Nunc@Fuscediam.co.uk","GLN50FUA9XW"),("Benedict","Jared","purus.mauris@molestietortornibh.com","MPU86EYO4MR");
INSERT INTO `utilisateur` (`nom`,`prenom`,`mail`,`mdp`) VALUES ("Jana","Michael","nunc.sed@cursus.edu","KOF60QKB6ZC"),("Rae","Ezekiel","faucibus@duiFuscediam.org","ZDQ52VCD1LT"),("Jade","Uriah","urna.Nullam.lobortis@anteiaculisnec.ca","YOZ47ZGD9KO"),("Channing","Castor","in.molestie@dictum.co.uk","CTQ59JAU7YE"),("Claire","Martena","Donec.elementum@Sedidrisus.co.uk","SDL27OGC1EN"),("Diana","Diana","ultrices.iaculis.odio@velquamdignissim.edu","SXE02BGF1RA"),("Grace","Piper","blandit@vitae.net","BKL84SOT2WI"),("Darrel","Beau","aliquet@justoPraesentluctus.net","MLW97GQX8UP"),("Leroy","Amal","nec.tempus@velturpis.co.uk","ZQY84JJZ1ZR"),("Rachel","Lysandra","sagittis@sed.com","YZD50JPP6EU");
INSERT INTO `utilisateur` (`nom`,`prenom`,`mail`,`mdp`) VALUES ("Devin","Bert","neque.non@vitae.ca","PYQ74MWH2KZ"),("Gretchen","Garth","justo.nec@tacitisociosquad.co.uk","LIE54FTX6XM"),("Keith","Anjolie","dictum.mi@urna.com","NZG91FYB2HU"),("Igor","Allistair","hendrerit.Donec@augueeutellus.org","MDH75IIL5CY"),("Barrett","Jocelyn","tellus.Nunc@insodaleselit.edu","TGR38QZC2IF"),("Quynn","Christopher","est@egetvolutpat.co.uk","NES70PQC9PI"),("Ariel","Jolene","felis@euismod.com","CDL86BAX8AP"),("MacKensie","Sophia","eros@dapibusligulaAliquam.com","TVI76EAH4UU"),("Cleo","Cassandra","vel.pede@diam.org","USK47JMX4FX"),("Angelica","Hamilton","semper@adipiscingMauris.co.uk","URR43DRC5CI");
INSERT INTO `utilisateur` (`nom`,`prenom`,`mail`,`mdp`) VALUES ("Charlotte","Stuart","Sed@vel.co.uk","WNB26WRQ4WU"),("Candice","Ira","cursus.vestibulum.Mauris@dapibus.org","CVN77ZSG7NY"),("Olivia","Ila","erat.volutpat.Nulla@egetmagna.org","QSU90QXN6UJ"),("Anjolie","Russell","elementum@Nuncsollicitudin.org","GMR18PBL4CO"),("Quinn","Sybill","eu.euismod.ac@augue.net","NBQ14XNZ4JN"),("Hilel","Kessie","massa@malesuadafames.com","XNT40LSL1YZ"),("Sylvia","Coby","quam.elementum@egestas.ca","SAB42UQR4VI"),("Regan","Willa","in.felis@ultrices.ca","AUD93NAA7SL"),("Nevada","Natalie","massa.non@auctorMauris.co.uk","VRL34NLY3YC"),("Claudia","Theodore","ipsum.cursus.vestibulum@consectetuerrhoncus.co.uk","INM41NLN8FG");
INSERT INTO `utilisateur` (`nom`,`prenom`,`mail`,`mdp`) VALUES ("Quentin","Jana","morbi@molestiearcu.ca","EQE11FZO1TP"),("Cody","Alexis","Sed@dictummiac.org","SRT62DCA8YY"),("Russell","Kaden","mattis@torquentper.co.uk","AID11VOP9LT"),("Raymond","Steel","at.velit.Pellentesque@nonummy.ca","MAI11BSD9VG"),("Emily","Kimberly","Aliquam@pharetraNam.ca","AOF12AHP5EQ"),("Dahlia","Eugenia","vel.est@interdum.org","TKK33GRH9TE"),("Zoe","Mari","dictum.eu@venenatis.net","XVG34OEL0EX"),("Sean","Rina","non.dui.nec@tinciduntDonec.edu","ETY32XWU3DR"),("Kameko","Upton","nascetur@dui.edu","TUV53IEB0FH"),("Anthony","Steel","Cras@magnaetipsum.net","POK94PVB6UB");
INSERT INTO `utilisateur` (`nom`,`prenom`,`mail`,`mdp`) VALUES ("Ifeoma","Lee","hendrerit.consectetuer.cursus@miDuis.edu","PVB03RJD5UC"),("Morgan","Pandora","dictum@mus.org","EFU57YLE9VB"),("Bianca","Rhea","ligula.Donec@eget.com","EWL62IFE8TQ"),("Adria","Gray","tincidunt.aliquam.arcu@liberoatauctor.net","OAX81DZO8VP"),("Carter","Cally","luctus@Nullamlobortis.edu","SIN92HFM2VW"),("Rudyard","Olivia","libero.dui@utsem.net","ULT64ZAO3XG"),("Lee","Anjolie","Morbi.vehicula.Pellentesque@egestasAliquamnec.co.uk","NXT53NQE8DO"),("Yetta","Irene","ut.pharetra.sed@sociisnatoquepenatibus.edu","HYC49KHZ8UH"),("Justina","Cassidy","Aliquam@dictumultricies.ca","JRU35SOE1WZ"),("Athena","Yael","tempor@Etiam.net","QVF40HIV7ON");
INSERT INTO `utilisateur` (`nom`,`prenom`,`mail`,`mdp`) VALUES ("Hashim","Aretha","fringilla.est@magnisdis.ca","EHM00FFH7AQ"),("Maia","Barrett","metus@velit.net","ZXD56PLT7VM"),("Brynn","Blossom","enim.condimentum@Uttinciduntorci.com","XVM39AAH3YO"),("Patrick","Kylee","dictum@Quisqueimperdiet.co.uk","PVQ77YHN8WM"),("Julie","Leigh","quam.Pellentesque@erosNamconsequat.org","AFG26NVP4SP"),("Emma","Athena","consectetuer.adipiscing@egetmetus.ca","CXA07UPJ7UM"),("Samantha","Karen","dui.Cras.pellentesque@risusDonecnibh.co.uk","AQS30SJW6YV"),("Shaine","Orli","lectus.Cum.sociis@sempertellus.ca","VMQ21NFK1DC"),("Sage","Abigail","quis.lectus@egetmassa.edu","YFN00UNE7DU"),("Tobias","Amal","eleifend.vitae.erat@Integereu.net","GPV26LBU0CI");
INSERT INTO `utilisateur` (`nom`,`prenom`,`mail`,`mdp`) VALUES ("Kylan","Shelby","lacus.Ut.nec@elementumat.org","ZEN01NOB5IX"),("Kadeem","Tatum","Nunc@neccursus.ca","NWE72JRG6SG"),("Jolie","Garrison","Cras@tempusrisus.edu","SSG83DJO0GI"),("Dorian","Tatyana","Proin@consequat.co.uk","IWY80VAB4YS"),("Amelia","Howard","mi@vitaeerat.ca","BTE42FKM6EE"),("Talon","Amy","vitae.erat.Vivamus@quisurna.co.uk","SRX71FHU8HG"),("Brenden","Abraham","et@noncursusnon.org","QQD22IAS7DK"),("Maxine","Basil","pharetra.Nam.ac@sagittisDuis.net","LVW27QQC7FT"),("Miranda","Leslie","eleifend.non.dapibus@velconvallisin.edu","TZL43QRO7TY"),("Indira","Jack","eros@acfacilisisfacilisis.net","OZX07BLA2CV");
INSERT INTO `utilisateur` (`nom`,`prenom`,`mail`,`mdp`) VALUES ("Wallace","Driscoll","odio.semper.cursus@Namligulaelit.co.uk","AWN28KQL0ZL"),("Jared","Fiona","ut@eros.co.uk","LLL64RRU7AB"),("Stephen","Mallory","ut.mi@consequatpurusMaecenas.co.uk","IBZ29PTX7MH"),("Yoshi","Raja","odio.Nam@pharetra.edu","PRB06UAE1FP"),("Shaeleigh","Jaquelyn","justo.nec.ante@laoreetlectusquis.net","LMM42HKA4MV"),("Eliana","Aladdin","purus.Duis.elementum@sem.com","IBV85CAH6JA"),("Yardley","Risa","sit.amet.ultricies@euligulaAenean.co.uk","LRB23JKH1BR"),("Zenaida","Fletcher","gravida.non@senectus.co.uk","LID85JMT8WU"),("Todd","Galvin","et.commodo.at@aliquet.ca","RJE31GHK7SN"),("Thor","Colette","Etiam@Donecvitaeerat.co.uk","PJQ40GUO0UL");


insert into `tarifs` values (null, 'abonnement_mensuel',50.99);
insert into `tarifs` values (null, 'abonnement_annuel',500.99);
insert into `tarifs` values (null, 'ticket_10_voyages',20.99);
insert into `tarifs` values (null, 'ticket_1_voyage',3);

insert into `abonnement` values(null,'2020-09-20','2021-01-20',2,1);
insert into `abonnement` values(null,'2021-02-12','2021-03-12',1,2);
insert into `abonnement` values(null,'2020-11-11','2020-12-11',1,3);
